# Generated by Django 3.2.7 on 2021-10-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='startingBid',
            new_name='current_price',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('HO', 'Home'), ('EL', 'Electronics'), ('FA', 'Fashion'), ('TO', 'Toys'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
