# Generated by Django 3.2.7 on 2021-10-04 06:08

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(auctions.models.get_sentinel_user), to='auctions.user'),
            preserve_default=False,
        ),
    ]
