# Generated by Django 3.2.7 on 2021-10-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_user_listing_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
