# Generated by Django 3.2.7 on 2021-10-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20211007_0600'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='Valid starting price.',
        ),
        migrations.RemoveConstraint(
            model_name='listing',
            name='Valid current price.',
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_price',
            field=models.FloatField(default=0.0),
        ),
    ]
